### ISSUE TITLE
Add ability to name devices on registration

### ISSUE THREAD

**Issue by knyghty** [Stormbase/django-otp-webauthn#47] opened 2024-12-12 13:00 UTC
Would be nice if users can name their passkeys on creation somehow. I can't find a way to do it at the moment without overriding stuff and making extra queries.

**Comment by AlmerCarbonEquity** [comment] 2024-12-12 13:53
Would also be great if by default the `name` field of the device gets populated with the source of the passkey e.g. iCloud. GitHub does this for example.

**Comment by Stormheg** [comment] 2024-12-15 15:41
I'd consider this a duplicate of #16.

In short: this currently is expected behavior because -- like django-otp[^1] -- django-otp-webauthn does not include any mechanism for managing devices besides registering and using them. The reason for this is that I wouldn't want django-otp-webauthn to be opinionated on how we prompt end-users for a name.

@AlmerCarbonEquity Autofilling a name based on what we can determine about the authenticator that created the Passkey sounds like a nice default. The difficulty with it is that (most) authenticators don't give you their AAGUID. They just pass an all-zero AAGUID for privacy preserving reasons.

We can influence this by setting the return value of [`get_attestation_conveyance_preference`](https://github.com/Stormbase/django-otp-webauthn/blob/bc727e9d50c435ec5aac61f5002810032a06968e/src/django_otp_webauthn/helpers.py#L150) to 'indirect' or 'direct' to request an attestation statement from the authenticator (basically, it provides a way to verify the authenticator that created the Passkey is 'genuine' - an enterprisey feature that requires frequent maintenance and effort to keep working properly). Under some conditions, this creates additional pop-ups like 'this site wants to read the make and model of your authenticator' which I don't want to bother users with. Overall, I don't want to set the preference to any value besides 'none' by default.

---

Back on topic: @knyghty see my (currently undocumented but supported approach) suggestion on https://github.com/Stormbase/django-otp-webauthn/issues/16#issuecomment-2262980927. It listens for JS events on the page to redirect somewhere. A 'name your Passkey' view for example.

If any of you have suggestions to make an unassuming 'ask for Passkey name' flow that comes with django-otp-webauthn, I'd love to hear it.

[^1]: https://django-otp-official.readthedocs.io/en/stable/auth.html#managing-devices

**Closed by Stormheg** 2024-12-15 15:41 UTC
